# Generated by Django 4.0.4 on 2022-05-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('odbyta', 'odbyta'), ('nieodbyta', 'nieodbyta'), ('anulowane', 'anulowana')], default='nieodbyta', max_length=100, unique=True),
        ),
    ]
