# Generated by Django 4.0.4 on 2022-06-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_alter_pet_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='address',
        ),
        migrations.AddField(
            model_name='producer',
            name='mail',
            field=models.EmailField(blank=True, max_length=1000, null=True),
        ),
    ]
