# Generated by Django 4.0.4 on 2022-05-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.ImageField(default='assets/svg/dog_avatar.svg', upload_to='pets_profile_pics'),
        ),
    ]
