# Generated by Django 4.0.4 on 2022-05-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_remove_treatment_end_alter_pet_year_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='producer',
        ),
        migrations.AddField(
            model_name='medicine',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.producer'),
        ),
    ]
