# Generated by Django 4.0.4 on 2022-05-26 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_medicinehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='medicine',
        ),
        migrations.AddField(
            model_name='medicinehistory',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.medicine'),
        ),
        migrations.AddField(
            model_name='medicinehistory',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.treatment'),
        ),
    ]
