# Generated by Django 4.0.4 on 2022-05-30 08:53

import aaConfig.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_remove_medicinehistory_expectedend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.ImageField(default='dog_avatar.png', upload_to='pet_profile_pics', validators=[aaConfig.validators.validate_file_size]),
        ),
    ]
