# Generated by Django 4.0.4 on 2022-05-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('startTime', models.TimeField(default=None)),
                ('endTime', models.TimeField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='doctor_avatar.png', upload_to='doctor_profile_pics'),
        ),
        migrations.CreateModel(
            name='DoctorShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.shift')),
            ],
        ),
    ]
